# Generated by Django 3.1.7 on 2022-01-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetailApp', '0002_auto_20220111_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
