# Generated by Django 3.1.7 on 2022-01-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetailApp', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RetailApp.category'),
            preserve_default=False,
        ),
    ]
