# Generated by Django 3.1.7 on 2022-01-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetailApp', '0004_product_product_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='product_cat',
        ),
    ]
